import { Clock3, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api/client";
import { Notice } from "../components/Notice";
import { useAuth } from "../hooks/useAuth";
import type { EventDetails, Seat, Show } from "../types";
import { errorMessage, money } from "../utils";

interface Hold { hold_id: string; expires_at: string; seat_ids: string[]; }

export function EventPage() {
  const { eventId } = useParams(); const { user } = useAuth();
  const [event, setEvent] = useState<EventDetails>(); const [show, setShow] = useState<Show>(); const [seats, setSeats] = useState<Seat[]>([]); const [selected, setSelected] = useState<string[]>([]); const [hold, setHold] = useState<Hold>(); const [outcome, setOutcome] = useState("SUCCESS"); const [notice, setNotice] = useState<{ text: string; error?: boolean }>(); const [remaining, setRemaining] = useState(0);
  useEffect(() => { api.get<EventDetails>(`/events/${eventId}`).then(({ data }) => { setEvent(data); if (data.shows[0]) setShow(data.shows[0]); }).catch((e) => setNotice({ text: errorMessage(e), error: true })); }, [eventId]);
  useEffect(() => { if (!show) return; api.get<{ seats: Seat[] }>(`/shows/${show.id}/seats`).then(({ data }) => { setSeats(data.seats); setSelected([]); setHold(undefined); }); }, [show]);
  useEffect(() => { if (!hold) return; const update = () => setRemaining(Math.max(0, Math.ceil((Date.parse(hold.expires_at) - Date.now()) / 1000))); update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, [hold]);
  const total = useMemo(() => selected.reduce((sum, id) => { const seat = seats.find((item) => item.id === id); const price = show?.prices.find((item) => item.category === seat?.category); return sum + (price?.amount_minor ?? 0); }, 0), [selected, seats, show]);
  const seatRows = useMemo(() => Object.values(seats.reduce<Record<string, Seat[]>>((rows, seat) => { const key = `${seat.section}:${seat.row}`; (rows[key] ??= []).push(seat); return rows; }, {})), [seats]);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length < 5 ? [...current, id] : current);
  const createHold = async () => { if (!user) return; try { const { data } = await api.post<Hold>("/holds", { show_id: show?.id, seat_ids: selected }); setHold(data); setNotice({ text: "Seats held. Complete the simulated checkout before the timer ends." }); } catch (e) { setNotice({ text: errorMessage(e), error: true }); } };
  const confirm = async () => { try { const key = crypto.randomUUID(); const response = await api.post("/bookings/confirm", { hold_id: hold?.hold_id, payment_outcome: outcome }, { headers: { "Idempotency-Key": key } }); setNotice({ text: response.data.message }); setHold(undefined); setSelected([]); const { data } = await api.get<{ seats: Seat[] }>(`/shows/${show?.id}/seats`); setSeats(data.seats); } catch (e) { setNotice({ text: errorMessage(e), error: true }); setHold(undefined); } };
  if (!event) return <p className="text-white/50">Loading event…</p>;
  return <div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="min-w-0"><p className="text-sm font-bold uppercase tracking-[.3em] text-mint">{event.category}</p><h1 className="mt-3 font-display text-6xl">{event.title}</h1><p className="mt-5 max-w-3xl text-lg text-white/55">{event.description}</p><div className="mt-10 flex flex-wrap gap-3">{event.shows.map((item) => <button key={item.id} onClick={() => setShow(item)} className={`rounded-xl border px-4 py-3 text-left ${show?.id === item.id ? "border-mint bg-mint/10" : "border-white/10 bg-panel"}`}><span className="block font-semibold">{new Date(item.starts_at).toLocaleDateString()}</span><span className="text-xs text-white/50">{new Date(item.starts_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} · {item.venue.name}</span></button>)}</div>
    <section className="mt-10 rounded-3xl border border-white/10 bg-panel p-6"><div className="mx-auto mb-10 w-2/3 rounded-b-[80%] border-t-4 border-mint/60 pt-4 text-center text-xs uppercase tracking-[.35em] text-white/30">Stage</div><div className="space-y-3 overflow-x-auto pb-2">{seatRows.map((row) => <div key={`${row[0].section}:${row[0].row}`} className="flex min-w-max items-center justify-center gap-2"><span className="w-16 text-right text-xs font-bold text-white/30">{row[0].section} {row[0].row}</span>{row.map((seat) => <button key={seat.id} disabled={seat.state !== "AVAILABLE" || !!hold} title={`${seat.identifier} · ${seat.category}`} onClick={() => toggle(seat.id)} className={`h-8 w-7 rounded-t-lg text-[10px] font-bold transition ${selected.includes(seat.id) ? "bg-mint text-ink ring-4 ring-mint/20" : seat.state === "BOOKED" ? "cursor-not-allowed bg-coral/25 text-coral" : seat.state === "HELD" ? "cursor-not-allowed bg-amber-300/20 text-amber-300" : "bg-white/10 hover:bg-white/20"}`}>{seat.number}</button>)}</div>)}</div><div className="mt-8 flex justify-center gap-5 text-xs text-white/45"><span>● Available</span><span className="text-amber-300">● Held</span><span className="text-coral">● Booked</span></div></section></div>
    <aside className="h-fit rounded-3xl border border-white/10 bg-panel p-6 lg:sticky lg:top-28"><h2 className="text-xl font-semibold">Your selection</h2><p className="mt-2 text-sm text-white/45">Choose up to five seats. Holds expire automatically.</p>{notice && <div className="mt-4"><Notice message={notice.text} tone={notice.error ? "error" : "success"} /></div>}<div className="my-6 space-y-2">{selected.map((id) => { const seat = seats.find((item) => item.id === id)!; return <div key={id} className="flex justify-between text-sm"><span>{seat.identifier} <small className="text-white/35">{seat.category}</small></span><span>{money(show?.prices.find((p) => p.category === seat.category)?.amount_minor ?? 0, show?.currency)}</span></div>; })}</div><div className="flex justify-between border-t border-white/10 pt-4 text-lg font-bold"><span>Total</span><span className="text-mint">{money(total, show?.currency)}</span></div>
      {!user ? <Link to="/login" className="mt-6 block rounded-xl bg-mint py-3 text-center font-bold text-ink">Sign in to hold seats</Link> : !hold ? <button disabled={!selected.length} onClick={() => void createHold()} className="mt-6 w-full rounded-xl bg-mint py-3 font-bold text-ink disabled:opacity-30">Hold {selected.length || ""} seat{selected.length === 1 ? "" : "s"}</button> : <><div className="mt-6 flex items-center justify-center gap-2 rounded-xl bg-coral/10 py-3 font-mono text-coral"><Clock3 size={18} /> {Math.floor(remaining / 60)}:{String(remaining % 60).padStart(2, "0")}</div><label className="mt-4 block text-xs text-white/45">Payment simulator outcome<select value={outcome} onChange={(e) => setOutcome(e.target.value)} className="input mt-2"><option value="SUCCESS">Success</option><option value="FAILURE">Failure</option><option value="TIMEOUT">Timeout</option></select></label><button disabled={!remaining} onClick={() => void confirm()} className="mt-4 w-full rounded-xl bg-coral py-3 font-bold text-ink disabled:opacity-30">Complete simulated payment</button></>}
      <p className="mt-5 flex gap-2 text-xs leading-relaxed text-white/35"><ShieldCheck className="shrink-0 text-mint" size={17} /> No card details or real money. PostgreSQL remains the final double-booking guard.</p></aside></div>;
}
