import { Download, PlusCircle } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { api } from "../api/client";
import { Notice } from "../components/Notice";
import { errorMessage, money } from "../utils";

interface Metrics { events: number; upcoming_shows: number; available_seats: number; confirmed_bookings: number; gross_revenue_minor: number; simulated_refunds_minor: number; net_revenue_minor: number; }

export function OrganizerPage() {
  const [metrics, setMetrics] = useState<Metrics>(); const [notice, setNotice] = useState(""); const [venueId, setVenueId] = useState(""); const [eventId, setEventId] = useState(""); const [showId, setShowId] = useState("");
  const load = () => api.get<Metrics>("/organizer/dashboard").then(({ data }) => setMetrics(data)).catch((e) => setNotice(errorMessage(e)));
  useEffect(() => { void load(); }, []);
  const createVenue = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const { data } = await api.post("/venues", { name: form.get("name"), city: form.get("city"), address: form.get("address"), sections: [{ name: form.get("section"), rows: [{ label: form.get("row"), seat_count: Number(form.get("seat_count")), category: form.get("category") }] }] }); setVenueId(data.id); setNotice(`Venue created: ${data.id}`); load(); } catch (e) { setNotice(errorMessage(e)); } };
  const createEvent = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const { data } = await api.post("/events", { title: form.get("title"), description: form.get("description"), category: form.get("category") }); setEventId(data.id); setNotice(`Event created: ${data.id}`); load(); } catch (e) { setNotice(errorMessage(e)); } };
  const createShow = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const start = new Date(String(form.get("starts_at"))); const { data } = await api.post(`/events/${form.get("event_id")}/shows`, { venue_id: form.get("venue_id"), starts_at: start.toISOString(), ends_at: new Date(start.getTime() + Number(form.get("duration")) * 3_600_000).toISOString(), currency: "INR", prices: [{ category: "STANDARD", amount_minor: Number(form.get("standard")) }, { category: "PREMIUM", amount_minor: Number(form.get("premium")) }, { category: "VIP", amount_minor: Number(form.get("vip")) }] }); setShowId(data.id); setNotice(`Show scheduled: ${data.id}`); load(); } catch (e) { setNotice(errorMessage(e)); } };
  const exportCsv = async () => { try { const { data } = await api.post(`/organizer/shows/${showId}/attendees/export`); setNotice(`CSV export queued. Export ID: ${data.export_id}. Open /api/v1/organizer/exports/${data.export_id} after the worker completes.`); } catch (e) { setNotice(errorMessage(e)); } };
  const cards = metrics ? [["Events", metrics.events], ["Upcoming shows", metrics.upcoming_shows], ["Available seats", metrics.available_seats], ["Confirmed", metrics.confirmed_bookings], ["Net simulated revenue", money(metrics.net_revenue_minor)]] : [];
  return <><div className="mb-10"><p className="text-sm font-bold uppercase tracking-[.3em] text-mint">Organizer command center</p><h1 className="mt-3 font-display text-6xl">Build the house.<br />Fill the house.</h1></div>{notice && <Notice message={notice} />}
    <div className="grid gap-4 md:grid-cols-5">{cards.map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-panel p-5"><p className="text-xs uppercase tracking-wider text-white/40">{label}</p><strong className="mt-2 block text-2xl text-mint">{value}</strong></div>)}</div>
    <div className="mt-10 grid gap-5 lg:grid-cols-3"><FormCard title="1. Create venue" onSubmit={createVenue}><input name="name" required className="input" placeholder="Venue name" /><input name="city" required className="input" placeholder="City" /><input name="address" required className="input" placeholder="Address" /><input name="section" required className="input" placeholder="Section name" defaultValue="Main" /><div className="grid grid-cols-2 gap-3"><input name="row" required className="input" placeholder="Row" defaultValue="A" /><input name="seat_count" required className="input" type="number" min="1" max="200" defaultValue="20" /></div><select name="category" className="input"><option>STANDARD</option><option>PREMIUM</option><option>VIP</option></select></FormCard>
      <FormCard title="2. Create event" onSubmit={createEvent}><input name="title" required className="input" placeholder="Event title" /><textarea name="description" required minLength={10} className="input min-h-28" placeholder="Description" /><input name="category" required className="input" placeholder="Category" /></FormCard>
      <FormCard title="3. Schedule show" onSubmit={createShow}><input name="event_id" required className="input" placeholder="Event ID" defaultValue={eventId} key={eventId} /><input name="venue_id" required className="input" placeholder="Venue ID" defaultValue={venueId} key={venueId} /><input name="starts_at" required type="datetime-local" className="input" /><input name="duration" required type="number" min="1" max="12" defaultValue="2" className="input" /><div className="grid grid-cols-3 gap-2"><input name="standard" required type="number" min="1" className="input" placeholder="Standard" /><input name="premium" required type="number" min="1" className="input" placeholder="Premium" /><input name="vip" required type="number" min="1" className="input" placeholder="VIP" /></div><p className="text-xs text-white/35">Prices are integer minor units.</p></FormCard></div>
    <section className="mt-6 flex flex-col gap-4 rounded-2xl border border-white/10 bg-panel p-6 md:flex-row md:items-end"><label className="flex-1 text-sm text-white/55">Show ID for attendee CSV<input className="input mt-2" value={showId} onChange={(e) => setShowId(e.target.value)} placeholder="Show ID" /></label><button disabled={!showId} onClick={() => void exportCsv()} className="flex items-center justify-center gap-2 rounded-xl bg-coral px-5 py-3 font-bold text-ink disabled:opacity-30"><Download size={18} /> Queue CSV export</button></section></>;
}

function FormCard({ title, onSubmit, children }: { title: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void; children: React.ReactNode }) {
  return <form onSubmit={onSubmit} className="space-y-3 rounded-2xl border border-white/10 bg-panel p-5"><h2 className="mb-4 flex items-center gap-2 font-semibold"><PlusCircle className="text-mint" size={18} /> {title}</h2>{children}<button className="w-full rounded-xl bg-mint py-3 font-bold text-ink">Save</button></form>;
}
